version: '3.1'
services:
  tomcat:
    restart: always
    #image: tomcat:jre8-temurin-focal
    image: tomcat:8.0-alpine
    container_name: tomcat
    ports:
      - 8484:8080
    volumes:
      - /usr/local/docker/tomcat/webapps:/usr/local/tomcat/webapps
    environment:
      TZ: Asia/Shanghai
  mysql:
    restart: always
    image: mysql:5.7.22
    container_name: mysql
    ports:
      - 3366:3306
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: 123456
    command:
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
      --explicit_defaults_for_timestamp=true
      --lower_case_table_names=1
      --max_allowed_packet=128M
      --sql-mode="STRICT_TRANS_TABLES,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION,NO_ZERO_DATE,NO_ZERO_IN_DATE,ERROR_FOR_DIVISION_BY_ZERO"
    volumes:
      - /usr/local/docker/mysql:/var/lib/mysql
